{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "gentleman.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "gentleman.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- range .Values.httpRoute.parentRefs }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
      {{- with .port }}
      port: {{ . }}
      {{- end }}
    {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ tpl . $ | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.httpRoute.rules }}
    {{- tpl (toYaml .Values.httpRoute.rules) . | nindent 4 }}
    {{- else }}
    - matches:
        - path:
            type: {{ .Values.httpRoute.pathType | default "PathPrefix" }}
            value: {{ .Values.httpRoute.path | default "/" }}
      {{- with .Values.httpRoute.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
    {{- end }}
{{- end }}
