{{- if and .Values.secrets.data (not .Values.secrets.create) (not .Values.secrets.existingSecret) }}
{{- fail "secrets.data is set but secrets.create is false. Set secrets.create=true, or use secrets.existingSecret." }}
{{- end }}

{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
{{- if .Values.secrets.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gentleman.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gentleman.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
{{- end }}
