apiVersion: v1
kind: Service
metadata:
  name: {{ include "gentleman.fullname" . }}
  labels:
    {{- include "gentleman.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "gentleman.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    name: http
